### ISSUE TITLE
Host (public) IP is not identified with provisioner "remote-exec" connection SSH

### ISSUE THREAD

**Issue by acloudiator** [btobolaski/terraform-provider-linode#9]
Using this as a resource with provisioner "remote-exec" fails to connect over SSH.

Here's my config and o/p; 

```
resource "linode_linode" "TEST" {
	image = "Fedora 25"
	kernel = "Latest 64 bit"
	name = "host1"
	group = "group1"
	region = "Fremont, CA, USA"
	size = 1024
	private_networking = true
	root_password = "abcxyz"

  provisioner "local-exec" {
    command = "sleep 30"
  }

  provisioner "remote-exec" {
      inline = [
        "hostnamectl set-hostname abc.local.com --static",
      ]
      connection {
        type     = "ssh"
        user     = "root"
        agent = "false"
        private_key = "${file("~/privatekey")}"
        }
    }
}
```

Output:
```
linode_linode.TEST (remote-exec): Connecting to remote host via SSH...
linode_linode.TEST (remote-exec):   Host:
linode_linode.TEST (remote-exec):   User: root
linode_linode.TEST (remote-exec):   Password: false
linode_linode.TEST (remote-exec):   Private key: true
linode_linode.TEST (remote-exec):   SSH Agent: false
```

**Comment by displague** [comment]
In another branch (against the terraform repo) I believe I addressed this bug with this:
https://github.com/hashicorp/terraform/commit/38e25e233f576c1adbe9a556afe4c6b55b6734ab

I'll see if the same needs to be done here.

**Comment by acloudiator** [comment]
Seems like soon terraform will have an official release for it :)

 BTW, I did a workaround under "provisioner -> connection" and it worked for me.

host  = "${linode_linode.TEST.ip_address}"

**Comment by acloudiator** [comment]
@displague - do you think this would be fixed?

**Comment by displague** [comment]
Hi @acloudiator, Thanks for reporting this!  See https://github.com/btobolaski/terraform-provider-linode/issues/2#issuecomment-430845369

Essentially, this bug is no longer a problem and you can use an official release which is based on this repository!

It may take a few more hours, but you should be able to `terraform init` a `provider "linode" {}` stanza without needing to clone and build the plugin.

See (and ⭐️ ) https://github.com/terraform-providers/terraform-provider-linode for more details.
